#ENC[AES256_GCM,data:CLQPJ14cJxoEvOaw1iAMhmO60mE/EBgZq/XW,iv:9i3fg7SlDw6gqE73ZLfcJXKITePNUrVo8xkiLMOAxMk=,tag:bhKL+h9nDdFKbJHwZzC5wg==,type:comment]
#ENC[AES256_GCM,data:oAGt4JX8sF9dgyCuJjOwEPQBqndiBr363oqesxE6jw==,iv:/NKI1yDMb82CM/5xeVy17JT1IWCNDoNSe/k3B2Y7ciY=,tag:hlOq11v5eagxVi2Bg6vLbA==,type:comment]
apiVersion: ENC[AES256_GCM,data:fM8=,iv:XF30DjtgKSnrW+OlQrYqGKcJl/TyVfG5anoav2mkIhw=,tag:k8FIRVktUQVCjd1FrfyPbg==,type:str]
data:
    #ENC[AES256_GCM,data:IiUvjOEWFHqU6dfZLLjSlEyQN6Vqlr5A4w==,iv:q2YDpJszmiNc5NUjj3pDKVGBNH/NAzrn65ps3CbUMwc=,tag:GSwvQ+8+7GZeX2n24ZNSlw==,type:comment]
    foo: null
kind: ENC[AES256_GCM,data:+ejmBV15,iv:lMBah+e3L4qUTm0REaVI5U1PlzxclQsrZ+lYlNOkhDU=,tag:T/qXrRJPZFv8vxPpOsauhw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:7ZzwTxhjecwH,iv:bxfL1IH5f44Gi0kFOLj0YmTG7ud1NbMc4XK1DbILOOs=,tag:+8ZKKrsHO0kmWurgJGYdSA==,type:str]
    namespace: ENC[AES256_GCM,data:u/4zwZwahA==,iv:oXgtzwAbH9bpLybuOpHUkYzyJI+MCvN+9bxNtPp2LSk=,tag:T3BldmkqxzPPshFW5wd/lA==,type:str]
type: ENC[AES256_GCM,data:ecjUEEhg,iv:mmFekNKzmFgi8YVhPmtdKjKaZUJMK2BxpvGiKoxDtkE=,tag:XKHntq2xDbc2aIOQIQ5aeA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u74ps32m3mcvd6zjaw8w2p3wwfucz0r2rxrsxmq8ldlyv5lapgkqle505u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3akRMUExreWkvUlNKQ1ZC
            Mm1Db3ZIWDVMYTQ5VzV1bXRZUjdJaHd2QVFzCk5tazY1UTQyZE9xVjNUYUdjZlVN
            eURYYzBWNEpKUy9wVlJTNkw0Qjg4MncKLS0tIEFvVUJkeGNvUlZkUGFIeVZDR0Z0
            dkhQbmhhTGc4NTBrR1lnOVBFZXZtdWcK9iDodGxjzgk7TIqNN1nCVMP7dipWA6RA
            QqM+W9ArO/3CswEBUf+sdLvg9HT1XRvnU2c264/WFIK3M22YCnz3tA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-02T20:47:01Z"
    mac: ENC[AES256_GCM,data:PRwWzlYsSWTog41e+fCNSdvFwuwaOTGMbyRTe4/kdNRwDjK2aZDu3wR8LqDGS1f3ziZYA4ZL0aGEbWc8nB8EXkqqq0FROdRu1ti+bkJvfdRSFRevWMkeBNphRCBA+Mtj6dduhAsvnoFoFYL+iTpZymwPEyBvztIYupRDwhfR2Ro=,iv:aWEWgh3znZBSe/d0yjAq5gK8mqiLy5aCgwtIa6Cl0Ao=,tag:/gws7HSRhpKY6dvqa9FHVQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
