apiVersion: ENC[AES256_GCM,data:fM8=,iv:XF30DjtgKSnrW+OlQrYqGKcJl/TyVfG5anoav2mkIhw=,tag:k8FIRVktUQVCjd1FrfyPbg==,type:str]
data:
    fooval: ENC[AES256_GCM,data:Fl/icXMz0tfDD4Cw,iv:781UHGFFvJJwGCzn/k5/J7PiMyukVJlKOZDx4dzy4Tg=,tag:R1jmgwNTxibrSX8TQ4A77g==,type:str]
kind: ENC[AES256_GCM,data:+ejmBV15,iv:lMBah+e3L4qUTm0REaVI5U1PlzxclQsrZ+lYlNOkhDU=,tag:T/qXrRJPZFv8vxPpOsauhw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:7ZzwTxhjecwH,iv:bxfL1IH5f44Gi0kFOLj0YmTG7ud1NbMc4XK1DbILOOs=,tag:+8ZKKrsHO0kmWurgJGYdSA==,type:str]
    namespace: ENC[AES256_GCM,data:u/4zwZwahA==,iv:oXgtzwAbH9bpLybuOpHUkYzyJI+MCvN+9bxNtPp2LSk=,tag:T3BldmkqxzPPshFW5wd/lA==,type:str]
type: ENC[AES256_GCM,data:ecjUEEhg,iv:mmFekNKzmFgi8YVhPmtdKjKaZUJMK2BxpvGiKoxDtkE=,tag:XKHntq2xDbc2aIOQIQ5aeA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u74ps32m3mcvd6zjaw8w2p3wwfucz0r2rxrsxmq8ldlyv5lapgkqle505u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3akRMUExreWkvUlNKQ1ZC
            Mm1Db3ZIWDVMYTQ5VzV1bXRZUjdJaHd2QVFzCk5tazY1UTQyZE9xVjNUYUdjZlVN
            eURYYzBWNEpKUy9wVlJTNkw0Qjg4MncKLS0tIEFvVUJkeGNvUlZkUGFIeVZDR0Z0
            dkhQbmhhTGc4NTBrR1lnOVBFZXZtdWcK9iDodGxjzgk7TIqNN1nCVMP7dipWA6RA
            QqM+W9ArO/3CswEBUf+sdLvg9HT1XRvnU2c264/WFIK3M22YCnz3tA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-03T01:04:49Z"
    mac: ENC[AES256_GCM,data:Nzdn4eJ+/fA00EO12jviXcCkZdUhBV6kX6SLwsXSLNXQZNFiYvDejSqCvwEFoz8AKkQWprSE1xzhf+Rj+gDmgUtcsXDk/BFWARS68qwss+WYA8ehjuyRlPOrZJFcAA4aJibNM+7NowQ/tlHKr/SW+Cfn5HpTE/bRCc4fbrldDa4=,iv:TmIC3z/gkytK22udQ6hZrF0GbdQ8ESp9V+2nTRVKkak=,tag:nthpvJ4ATY3BetF73PTIww==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
