apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: where-for-dinner-ingress
  namespace: default
spec:
  virtualhost:
    fqdn: where-for-dinner.<UPDATE ME>
  routes:
  - conditions:
    - prefix: /
    services:
    - name: gateway-where-for-dinner
      port: 80
